[package]
name = "procgen-geology"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
procgen-core = { path = "../procgen-core" }
procgen-sphere-mesh = { path = "../procgen-sphere-mesh" }
procgen-tectonics = { path = "../procgen-tectonics" }

[dev-dependencies]
procgen-sphere = { path = "../procgen-sphere" }
