[package]
name = "procgen-raster-tectonics"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
bytemuck = { version = "1.24", features = ["derive"] }
procgen-core = { path = "../procgen-core" }
procgen-cubesphere = { path = "../procgen-cubesphere" }
procgen-tectonics = { path = "../procgen-tectonics" }
wgpu = { version = "27.0.1", default-features = false, features = [
    "dx12",
    "metal",
    "std",
    "vulkan",
    "wgsl",
] }
