[package]
name = "procgen-terrain"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
procgen-core = { path = "../procgen-core" }
procgen-cubesphere = { path = "../procgen-cubesphere" }
procgen-geology = { path = "../procgen-geology" }
procgen-noise = { path = "../procgen-noise" }
procgen-sphere-mesh = { path = "../procgen-sphere-mesh" }
procgen-tectonics = { path = "../procgen-tectonics" }
rayon = "1"

[dev-dependencies]
procgen-sphere = { path = "../procgen-sphere" }
