mod compute;
mod coverage;
mod residency;

use std::collections::HashMap;
use std::sync::{
    Arc,
    atomic::{AtomicU32, Ordering},
};

use coverage::{CoverageView, QuadtreeSelection, tile_morph_factor};
use residency::{ResidentTile, TileResidency};

use super::{
    DiagnosticLayer, ReliefSettings, SURFACE_RADIUS, SurfaceSelection,
    palette::ELEVATION_COLOR_STOPS,
};
use crate::{camera::ViewerCamera, model::GeneratedWorld};
use bevy::{
    asset::{RenderAssetUsages, uuid_handle},
    camera::{Camera, Projection, visibility::NoFrustumCulling},
    ecs::system::SystemParam,
    mesh::{Indices, MeshTag, PrimitiveTopology},
    pbr::{ExtendedMaterial, MaterialExtension},
    prelude::*,
    render::{
        RenderApp,
        extract_resource::{ExtractResource, ExtractResourcePlugin},
        render_resource::{AsBindGroup, ShaderType},
        storage::ShaderStorageBuffer,
    },
    shader::{Shader, ShaderRef},
};
use procgen_cubesphere::{MAPPING_WGSL_SOURCE, TILE_QUADS, TILE_VERTICES};
use procgen_terrain::{
    TERRAIN_TILE_SAMPLE_COUNT, TERRAIN_WGSL_SOURCE, TerrainGpuParameters, TerrainGpuStamp,
    TerrainHeightConfig, TerrainNoiseKeys, pack_control_bake, pack_stamps,
};

/// Camera distance at or below which adjusted elevation uses GPU terrain tiles.
const TERRAIN_TILE_ZOOM_THRESHOLD: f32 = 1.75;
const TERRAIN_MAX_TILE_LEVEL: u8 = 12;

/// Next power-of-two capacity above the measured 982-tile close-view handoff demand.
const MAX_RESIDENT_TILES: usize = 1_024;
/// Maximum number of new terrain tiles generated by the viewer in one frame.
const NEW_TERRAIN_TILES_PER_FRAME: usize = 8;
/// Radial skirt depth in units of the tile's nominal vertex spacing.
const TERRAIN_SKIRT_DEPTH_SPACINGS: f32 = 2.0;
const TERRAIN_SAMPLE_CAPACITY: usize = MAX_RESIDENT_TILES * TERRAIN_TILE_SAMPLE_COUNT;
const ELEVATION_PALETTE_STOP_COUNT: usize = ELEVATION_COLOR_STOPS.len();
const TERRAIN_SLOT_BITS: u32 = MAX_RESIDENT_TILES.trailing_zeros();
const TERRAIN_SLOT_MASK: u32 = MAX_RESIDENT_TILES as u32 - 1;
const TERRAIN_MORPH_BITS: u32 = u32::BITS - 2 * TERRAIN_SLOT_BITS;
const TERRAIN_MORPH_MAX: u32 = (1 << TERRAIN_MORPH_BITS) - 1;

const _: () = assert!(MAX_RESIDENT_TILES.is_power_of_two());

const TERRAIN_VERTEX_SHADER: Handle<Shader> = uuid_handle!("f793fce0-ef68-49dd-8c98-7bba8432bc76");
const TERRAIN_COMPUTE_SHADER: Handle<Shader> = uuid_handle!("c7c57793-ae7c-4eb7-a1a9-9b8fb2d5a651");

#[derive(Clone, Copy, Debug, ShaderType)]
struct TerrainDisplayParameters {
    relief_exaggeration: f32,
    surface_radius: f32,
    padding: Vec2,
}

#[derive(Clone, Copy, Debug, ShaderType)]
struct TerrainElevationPalette {
    stops: [Vec4; ELEVATION_PALETTE_STOP_COUNT],
}

#[derive(Asset, AsBindGroup, Clone, Debug, TypePath)]
struct TerrainTileExtension {
    #[storage(100, read_only)]
    addresses: Handle<ShaderStorageBuffer>,
    #[storage(101, read_only)]
    samples: Handle<ShaderStorageBuffer>,
    #[uniform(102)]
    display: TerrainDisplayParameters,
    #[uniform(103)]
    palette: TerrainElevationPalette,
}

impl MaterialExtension for TerrainTileExtension {
    fn vertex_shader() -> ShaderRef {
        TERRAIN_VERTEX_SHADER.into()
    }
}

type TerrainTileMaterial = ExtendedMaterial<StandardMaterial, TerrainTileExtension>;

#[derive(Resource, Clone, ExtractResource)]
struct TerrainGpuResources {
    controls: Handle<ShaderStorageBuffer>,
    stamps: Handle<ShaderStorageBuffer>,
    parameters: Handle<ShaderStorageBuffer>,
    jobs: Handle<ShaderStorageBuffer>,
    addresses: Handle<ShaderStorageBuffer>,
    samples: Handle<ShaderStorageBuffer>,
}

#[derive(Resource)]
struct TerrainTileAssets {
    material: Handle<TerrainTileMaterial>,
}

#[derive(Resource, Clone, ExtractResource, Default)]
struct TerrainTileDispatch {
    job_count: u32,
    generation: u32,
    completed_generation: Arc<AtomicU32>,
}

impl TerrainTileDispatch {
    fn is_complete(&self) -> bool {
        self.completed_generation.load(Ordering::Acquire) == self.generation
    }
}

#[repr(C, align(16))]
#[derive(Clone, Copy, Debug, PartialEq, Eq, bytemuck::Pod, bytemuck::Zeroable)]
struct TerrainTileJob {
    address: [u32; 4],
    destination: [u32; 4],
}

#[derive(Resource, Default)]
struct TerrainTileCoverage(HashMap<ResidentTile, Entity>);

#[derive(Resource, Clone, Copy, Debug, Default, PartialEq, Eq)]
pub(super) enum TerrainTileMode {
    #[default]
    Coarse,
    Tiles,
}

#[derive(Resource)]
struct TerrainGridMesh(Handle<Mesh>);

pub(super) struct TerrainTileRenderPlugin;

impl Plugin for TerrainTileRenderPlugin {
    fn build(&self, app: &mut App) {
        register_shaders(app);
        app.add_plugins((
            MaterialPlugin::<TerrainTileMaterial>::default(),
            ExtractResourcePlugin::<TerrainGpuResources>::default(),
            ExtractResourcePlugin::<TerrainTileDispatch>::default(),
        ))
        .init_resource::<TerrainTileCoverage>()
        .init_resource::<TerrainTileDispatch>()
        .init_resource::<TerrainTileMode>()
        .init_resource::<QuadtreeSelection>()
        .init_resource::<TileResidency>()
        .add_systems(Startup, initialize_grid_mesh)
        .add_systems(
            Update,
            (
                initialize_gpu_world.run_if(resource_changed::<GeneratedWorld>),
                sync_mode.run_if(resource_changed::<SurfaceSelection>.or(camera_changed)),
                sync_relief.run_if(
                    resource_changed::<ReliefSettings>.and(resource_exists::<TerrainTileAssets>),
                ),
                update_tile_coverage.run_if(
                    resource_changed::<GeneratedWorld>
                        .or(resource_changed::<TerrainTileMode>)
                        .or(camera_changed)
                        .or(terrain_dispatch_completed),
                ),
            )
                .chain(),
        );

        compute::install(app.sub_app_mut(RenderApp));
    }
}

fn camera_changed(camera: Single<Ref<Transform>, With<ViewerCamera>>) -> bool {
    camera.is_changed()
}

fn terrain_dispatch_completed(
    dispatch: Res<TerrainTileDispatch>,
    mut observed: Local<u32>,
) -> bool {
    let changed = dispatch.is_complete() && dispatch.generation != *observed;
    if changed {
        *observed = dispatch.generation;
    }
    changed
}

pub(super) fn sync_mode(
    camera: Single<&Transform, With<ViewerCamera>>,
    selection: Res<SurfaceSelection>,
    mut mode: ResMut<TerrainTileMode>,
) {
    mode.set_if_neq(terrain_tile_mode(
        camera.translation.length(),
        selection.selected(),
    ));
}

fn initialize_grid_mesh(mut commands: Commands, mut meshes: ResMut<Assets<Mesh>>) {
    commands.insert_resource(TerrainGridMesh(meshes.add(tile_grid_mesh())));
}

fn register_shaders(app: &mut App) {
    let vertex_source = format!(
        "{MAPPING_WGSL_SOURCE}\nconst TERRAIN_ELEVATION_PALETTE_STOP_COUNT: u32 = {ELEVATION_PALETTE_STOP_COUNT}u;\nconst TERRAIN_SKIRT_DEPTH_SPACINGS: f32 = {TERRAIN_SKIRT_DEPTH_SPACINGS};\nconst TERRAIN_SLOT_BITS: u32 = {TERRAIN_SLOT_BITS}u;\nconst TERRAIN_SLOT_MASK: u32 = {TERRAIN_SLOT_MASK}u;\nconst TERRAIN_MORPH_MAX: u32 = {TERRAIN_MORPH_MAX}u;\n{}",
        include_str!("terrain_tiles.wgsl")
    );
    let compute_source = format!(
        "{TERRAIN_WGSL_SOURCE}\n{}",
        include_str!("terrain_compute.wgsl")
    );
    let mut shaders = app.world_mut().resource_mut::<Assets<Shader>>();
    shaders
        .insert(
            TERRAIN_VERTEX_SHADER.id(),
            Shader::from_wgsl(vertex_source, "procgen-terrain-viewer.wgsl"),
        )
        .unwrap();
    shaders
        .insert(
            TERRAIN_COMPUTE_SHADER.id(),
            Shader::from_wgsl(compute_source, "procgen-terrain-compute.wgsl"),
        )
        .unwrap();
}

#[derive(SystemParam)]
struct TerrainWorldAssets<'w, 's> {
    commands: Commands<'w, 's>,
    coverage: ResMut<'w, TerrainTileCoverage>,
    buffers: ResMut<'w, Assets<ShaderStorageBuffer>>,
    materials: ResMut<'w, Assets<TerrainTileMaterial>>,
    selection: ResMut<'w, QuadtreeSelection>,
    residency: ResMut<'w, TileResidency>,
    dispatch: ResMut<'w, TerrainTileDispatch>,
}

fn initialize_gpu_world(
    world: Res<GeneratedWorld>,
    relief: Res<ReliefSettings>,
    mut assets: TerrainWorldAssets,
) {
    for (_, entity) in assets.coverage.0.drain() {
        assets.commands.entity(entity).despawn();
    }
    assets.selection.clear();
    *assets.residency = TileResidency::default();
    assets.dispatch.job_count = 0;
    assets.dispatch.generation = assets.dispatch.generation.wrapping_add(1);

    let controls = pack_control_bake(&world.terrain_control_bake);
    let mut stamps = pack_stamps(&world.terrain_controls.stamps);
    // wgpu storage bindings cannot be empty; the shader reads no stamps when stamp_count is zero.
    if stamps.is_empty() {
        stamps.push(TerrainGpuStamp {
            position: [0.0; 3],
            strength: 0.0,
            kind: 0,
            padding: [0; 3],
        });
    }
    let parameters = TerrainGpuParameters::new(
        &world.terrain_control_bake,
        &world.terrain_controls.stamps,
        TerrainNoiseKeys::new(world.config.fibonacci.seed),
        TerrainHeightConfig::default(),
    );
    let controls = assets.buffers.add(ShaderStorageBuffer::new(
        bytemuck::cast_slice(&controls),
        RenderAssetUsages::default(),
    ));
    let stamps = assets.buffers.add(ShaderStorageBuffer::new(
        bytemuck::cast_slice(&stamps),
        RenderAssetUsages::default(),
    ));
    let parameters = assets.buffers.add(ShaderStorageBuffer::new(
        bytemuck::bytes_of(&parameters),
        RenderAssetUsages::default(),
    ));
    // wgpu storage bindings cannot be empty; this placeholder is never dispatched.
    let jobs = assets.buffers.add(ShaderStorageBuffer::new(
        bytemuck::bytes_of(&TerrainTileJob {
            address: [0; 4],
            destination: [0; 4],
        }),
        RenderAssetUsages::default(),
    ));
    let addresses = assets.buffers.add(ShaderStorageBuffer::with_size(
        MAX_RESIDENT_TILES * size_of::<[u32; 4]>(),
        RenderAssetUsages::default(),
    ));
    let samples = assets.buffers.add(ShaderStorageBuffer::with_size(
        TERRAIN_SAMPLE_CAPACITY * size_of::<Vec4>(),
        RenderAssetUsages::default(),
    ));
    let material = assets.materials.add(ExtendedMaterial {
        base: StandardMaterial {
            base_color: Color::WHITE,
            perceptual_roughness: 1.0,
            ..default()
        },
        extension: TerrainTileExtension {
            addresses: addresses.clone(),
            samples: samples.clone(),
            display: TerrainDisplayParameters {
                relief_exaggeration: relief.exaggeration,
                surface_radius: SURFACE_RADIUS,
                padding: Vec2::ZERO,
            },
            palette: elevation_palette(),
        },
    });
    assets.commands.insert_resource(TerrainGpuResources {
        controls,
        stamps,
        parameters,
        jobs,
        addresses,
        samples,
    });
    assets
        .commands
        .insert_resource(TerrainTileAssets { material });
}

fn elevation_palette() -> TerrainElevationPalette {
    TerrainElevationPalette {
        stops: std::array::from_fn(|index| {
            let (value, color) = ELEVATION_COLOR_STOPS[index];
            Vec4::new(color.x, color.y, color.z, value)
        }),
    }
}

#[derive(SystemParam)]
struct TerrainCoverageAssets<'w, 's> {
    commands: Commands<'w, 's>,
    grid: Res<'w, TerrainGridMesh>,
    coverage: ResMut<'w, TerrainTileCoverage>,
    selection: ResMut<'w, QuadtreeSelection>,
    residency: ResMut<'w, TileResidency>,
    dispatch: ResMut<'w, TerrainTileDispatch>,
    resources: ResMut<'w, TerrainGpuResources>,
    tile_assets: Res<'w, TerrainTileAssets>,
    buffers: ResMut<'w, Assets<ShaderStorageBuffer>>,
}

fn sync_relief(
    relief: Res<ReliefSettings>,
    tile_assets: Res<TerrainTileAssets>,
    mut materials: ResMut<Assets<TerrainTileMaterial>>,
) {
    materials
        .get_mut(&tile_assets.material)
        .expect("terrain tile material must remain alive")
        .extension
        .display
        .relief_exaggeration = relief.exaggeration;
}

fn update_tile_coverage(
    camera: Single<(&Camera, &Projection, &Transform), With<ViewerCamera>>,
    mode: Res<TerrainTileMode>,
    mut assets: TerrainCoverageAssets,
) {
    if assets.dispatch.is_complete() {
        assets.residency.complete_in_flight();
    }
    let view = if *mode == TerrainTileMode::Tiles {
        let (camera, projection, transform) = *camera;
        let Some(view) = CoverageView::from_camera(camera, projection, transform) else {
            return;
        };
        Some(view)
    } else {
        None
    };
    let targets = if let Some(view) = view {
        assets.selection.select(view)
    } else {
        assets.selection.clear();
        Vec::new()
    };
    let update = assets.residency.update(&targets);
    upload_generation_jobs(&update.generated, &mut assets);
    sync_displayed_tiles(&update.displayed, view, &mut assets);
}

fn upload_generation_jobs(generated: &[ResidentTile], assets: &mut TerrainCoverageAssets) {
    if generated.is_empty() {
        return;
    }
    assets.resources.jobs = assets.buffers.add(ShaderStorageBuffer::new(
        bytemuck::cast_slice(&generation_jobs(generated)),
        RenderAssetUsages::default(),
    ));
    assets.dispatch.generation = assets.dispatch.generation.wrapping_add(1);
    assets.dispatch.job_count = generated.len() as u32;
}

fn generation_jobs(generated: &[ResidentTile]) -> Vec<TerrainTileJob> {
    generated
        .iter()
        .map(|tile| TerrainTileJob {
            address: tile.address.gpu_words(),
            destination: [tile.slot, 0, 0, 0],
        })
        .collect()
}

fn sync_displayed_tiles(
    displayed: &[ResidentTile],
    view: Option<CoverageView>,
    assets: &mut TerrainCoverageAssets,
) {
    let mut previous = std::mem::take(&mut assets.coverage.0);
    let mesh = assets.grid.0.clone();
    let material = assets.tile_assets.material.clone();
    assets.coverage.0 = displayed
        .iter()
        .copied()
        .map(|tile| {
            let (parent_slot, morph) = match (assets.residency.ready_parent_slot(tile), view) {
                (Some(parent_slot), Some(view)) => {
                    (parent_slot, tile_morph_factor(tile.address, view))
                }
                (Some(parent_slot), None) => (parent_slot, 1.0),
                (None, _) => (tile.slot, 1.0),
            };
            let tag = terrain_mesh_tag(tile, parent_slot, morph);
            if let Some(entity) = previous.remove(&tile) {
                assets.commands.entity(entity).insert(MeshTag(tag));
                return (tile, entity);
            }
            let entity = assets
                .commands
                .spawn((
                    Mesh3d(mesh.clone()),
                    MeshMaterial3d(material.clone()),
                    MeshTag(tag),
                    Transform::from_translation(tile_origin(tile.address)),
                    NoFrustumCulling,
                ))
                .id();
            (tile, entity)
        })
        .collect();
    for (_, entity) in previous {
        assets.commands.entity(entity).despawn();
    }
}

fn terrain_mesh_tag(tile: ResidentTile, parent_slot: u32, morph: f32) -> u32 {
    assert!(tile.slot <= TERRAIN_SLOT_MASK);
    assert!(parent_slot <= TERRAIN_SLOT_MASK);
    assert!(morph.is_finite() && (0.0..=1.0).contains(&morph));
    let quantized_morph = (morph * TERRAIN_MORPH_MAX as f32).round() as u32;
    tile.slot | (parent_slot << TERRAIN_SLOT_BITS) | (quantized_morph << (2 * TERRAIN_SLOT_BITS))
}

fn terrain_tile_mode(camera_distance: f32, selected: Option<DiagnosticLayer>) -> TerrainTileMode {
    if camera_distance <= TERRAIN_TILE_ZOOM_THRESHOLD
        && selected == Some(DiagnosticLayer::IsostaticElevation)
    {
        TerrainTileMode::Tiles
    } else {
        TerrainTileMode::Coarse
    }
}

fn tile_grid_mesh() -> Mesh {
    // Integer grid coordinates are decoded by the custom vertex shader; normals and colors are
    // present only to select Bevy's lit, vertex-color mesh pipeline layout.
    let mut positions = (0..TILE_VERTICES)
        .flat_map(|y| (0..TILE_VERTICES).map(move |x| [x as f32, y as f32, 0.0]))
        .collect::<Vec<_>>();
    let mut indices = Vec::with_capacity(((TILE_QUADS * TILE_QUADS + 4 * TILE_QUADS) * 6) as usize);
    for y in 0..TILE_QUADS {
        for x in 0..TILE_QUADS {
            let lower_left = y * TILE_VERTICES + x;
            let lower_right = lower_left + 1;
            let upper_left = lower_left + TILE_VERTICES;
            let upper_right = upper_left + 1;
            indices.extend([
                lower_left,
                lower_right,
                upper_right,
                lower_left,
                upper_right,
                upper_left,
            ]);
        }
    }
    append_skirt_edge(
        &mut positions,
        &mut indices,
        (0..TILE_VERTICES).map(|x| (x, 0)),
        false,
    );
    append_skirt_edge(
        &mut positions,
        &mut indices,
        (0..TILE_VERTICES).map(|y| (TILE_QUADS, y)),
        false,
    );
    append_skirt_edge(
        &mut positions,
        &mut indices,
        (0..TILE_VERTICES).map(|x| (x, TILE_QUADS)),
        true,
    );
    append_skirt_edge(
        &mut positions,
        &mut indices,
        (0..TILE_VERTICES).map(|y| (0, y)),
        true,
    );
    let normals = vec![[0.0, 0.0, 1.0]; positions.len()];
    let colors = vec![[1.0, 1.0, 1.0, 1.0]; positions.len()];
    Mesh::new(
        PrimitiveTopology::TriangleList,
        RenderAssetUsages::default(),
    )
    .with_inserted_attribute(Mesh::ATTRIBUTE_POSITION, positions)
    .with_inserted_attribute(Mesh::ATTRIBUTE_NORMAL, normals)
    .with_inserted_attribute(Mesh::ATTRIBUTE_COLOR, colors)
    .with_inserted_indices(Indices::U32(indices))
}

fn append_skirt_edge(
    positions: &mut Vec<[f32; 3]>,
    indices: &mut Vec<u32>,
    edge: impl Iterator<Item = (u32, u32)>,
    reverse_winding: bool,
) {
    let edge = edge.collect::<Vec<_>>();
    let skirt_start = positions.len() as u32;
    positions.extend(edge.iter().map(|&(x, y)| [x as f32, y as f32, 1.0]));
    for (offset, pair) in edge.windows(2).enumerate() {
        let core = [
            pair[0].1 * TILE_VERTICES + pair[0].0,
            pair[1].1 * TILE_VERTICES + pair[1].0,
        ];
        let skirt = [skirt_start + offset as u32, skirt_start + offset as u32 + 1];
        if reverse_winding {
            indices.extend([core[0], core[1], skirt[1], core[0], skirt[1], skirt[0]]);
        } else {
            indices.extend([core[0], skirt[1], core[1], core[0], skirt[0], skirt[1]]);
        }
    }
}

fn tile_origin(address: procgen_cubesphere::TileAddress) -> Vec3 {
    coverage::tile_direction(address, TILE_QUADS / 2, TILE_QUADS / 2) * SURFACE_RADIUS
}

#[cfg(test)]
mod tests {
    use super::*;
    use bevy::mesh::VertexAttributeValues;
    use procgen_cubesphere::{CubeFace, TileAddress};

    use super::coverage::tile_direction;

    #[test]
    fn tile_grid_triangles_face_outward_on_every_cube_face() {
        let mesh = tile_grid_mesh();
        let VertexAttributeValues::Float32x3(positions) =
            mesh.attribute(Mesh::ATTRIBUTE_POSITION).unwrap()
        else {
            panic!("terrain tile positions must be float3");
        };
        let Indices::U32(indices) = mesh.indices().unwrap() else {
            panic!("terrain tile indices must be u32");
        };

        for face in CubeFace::ALL {
            let address = TileAddress::root(face);
            for triangle in indices[..(TILE_QUADS * TILE_QUADS * 6) as usize].chunks_exact(3) {
                let directions = [triangle[0], triangle[1], triangle[2]].map(|index| {
                    let [x, y, _] = positions[index as usize];
                    tile_direction(address, x as u32, y as u32)
                });
                let geometric_normal =
                    (directions[1] - directions[0]).cross(directions[2] - directions[0]);
                let center = (directions[0] + directions[1] + directions[2]).normalize();
                assert!(geometric_normal.dot(center) > 0.0);
            }
        }
    }

    #[test]
    fn skirt_is_one_quad_deep_uses_edge_samples_and_winds_outward() {
        let mesh = tile_grid_mesh();
        let VertexAttributeValues::Float32x3(positions) =
            mesh.attribute(Mesh::ATTRIBUTE_POSITION).unwrap()
        else {
            panic!("terrain tile positions must be float3");
        };
        let Indices::U32(indices) = mesh.indices().unwrap() else {
            panic!("terrain tile indices must be u32");
        };
        assert_eq!(
            positions.len(),
            (TILE_VERTICES * TILE_VERTICES + 4 * TILE_VERTICES) as usize
        );
        assert_eq!(
            indices.len(),
            ((TILE_QUADS * TILE_QUADS + 4 * TILE_QUADS) * 6) as usize
        );
        let core_indices = (TILE_QUADS * TILE_QUADS * 6) as usize;
        let address = TileAddress::root(CubeFace::PositiveZ);
        let center = tile_origin(address);
        let skirt_depth = TERRAIN_SKIRT_DEPTH_SPACINGS * std::f32::consts::FRAC_PI_2
            / (TILE_QUADS << address.level()) as f32;
        for triangle in indices[core_indices..].chunks_exact(3) {
            let world = [triangle[0], triangle[1], triangle[2]].map(|index| {
                let [x, y, skirt] = positions[index as usize];
                tile_direction(address, x as u32, y as u32) * (1.0 - skirt * skirt_depth)
            });
            let normal = (world[1] - world[0]).cross(world[2] - world[0]);
            let edge_direction = (world[0] + world[1] + world[2]).normalize();
            let away_from_center = edge_direction - center;
            assert!(normal.dot(away_from_center) > 0.0);
            let skirt_vertices = triangle
                .iter()
                .filter(|&&index| positions[index as usize][2] == 1.0)
                .count();
            assert!((1..=2).contains(&skirt_vertices));
        }
    }

    #[test]
    fn level_twelve_relative_positions_reconstruct_world_positions() {
        let address = TileAddress::new(CubeFace::NegativeY, 12, 1_913, 2_077).unwrap();
        let origin = tile_origin(address);
        for (x, y) in [(0, 0), (32, 32), (64, 64)] {
            let world = tile_direction(address, x, y) * SURFACE_RADIUS;
            let relative = world - origin;
            let reconstructed = origin + relative;
            assert!(reconstructed.distance(world) <= f32::EPSILON);
            assert!(relative.length() < 0.001);
        }
    }

    #[test]
    fn mode_only_replaces_final_adjusted_elevation_below_threshold() {
        assert_eq!(
            terrain_tile_mode(
                TERRAIN_TILE_ZOOM_THRESHOLD,
                Some(DiagnosticLayer::IsostaticElevation)
            ),
            TerrainTileMode::Tiles
        );
        assert_eq!(
            terrain_tile_mode(
                TERRAIN_TILE_ZOOM_THRESHOLD + f32::EPSILON,
                Some(DiagnosticLayer::IsostaticElevation)
            ),
            TerrainTileMode::Coarse
        );
        assert_eq!(
            terrain_tile_mode(1.25, Some(DiagnosticLayer::GeologicalElevation)),
            TerrainTileMode::Coarse
        );
        assert_eq!(terrain_tile_mode(1.25, None), TerrainTileMode::Coarse);
    }

    #[test]
    fn mode_resource_changes_only_when_the_rendering_mode_changes() {
        let mut app = App::new();
        app.init_resource::<SurfaceSelection>()
            .init_resource::<TerrainTileMode>()
            .add_systems(Update, sync_mode);
        let camera = app
            .world_mut()
            .spawn((Transform::from_xyz(0.0, 0.0, 3.2), ViewerCamera))
            .id();

        app.update();
        assert_eq!(
            *app.world().resource::<TerrainTileMode>(),
            TerrainTileMode::Coarse
        );
        app.world_mut().clear_trackers();
        app.update();
        assert!(!app.world().resource_ref::<TerrainTileMode>().is_changed());

        app.world_mut()
            .entity_mut(camera)
            .get_mut::<Transform>()
            .unwrap()
            .translation = Vec3::Z * TERRAIN_TILE_ZOOM_THRESHOLD;
        app.update();
        assert_eq!(
            *app.world().resource::<TerrainTileMode>(),
            TerrainTileMode::Tiles
        );
    }

    #[test]
    fn completion_condition_runs_once_per_finished_generation() {
        #[derive(Resource, Default)]
        struct Runs(u32);

        fn count_run(mut runs: ResMut<Runs>) {
            runs.0 += 1;
        }

        let mut app = App::new();
        app.init_resource::<TerrainTileDispatch>()
            .init_resource::<Runs>()
            .add_systems(Update, count_run.run_if(terrain_dispatch_completed));
        app.update();
        assert_eq!(app.world().resource::<Runs>().0, 0);

        let mut dispatch = app.world_mut().resource_mut::<TerrainTileDispatch>();
        dispatch.generation = 1;
        dispatch.completed_generation.store(1, Ordering::Release);
        app.update();
        app.update();
        assert_eq!(app.world().resource::<Runs>().0, 1);

        let mut dispatch = app.world_mut().resource_mut::<TerrainTileDispatch>();
        dispatch.generation = 2;
        app.update();
        assert_eq!(app.world().resource::<Runs>().0, 1);
        app.world()
            .resource::<TerrainTileDispatch>()
            .completed_generation
            .store(2, Ordering::Release);
        app.update();
        assert_eq!(app.world().resource::<Runs>().0, 2);
    }

    #[test]
    fn world_replacement_resets_coverage_and_world_owned_gpu_resources() {
        use crate::test_support::fixture;
        use bevy::asset::{AssetApp, AssetPlugin};

        let mut app = App::new();
        app.add_plugins(AssetPlugin::default())
            .init_asset::<ShaderStorageBuffer>()
            .init_asset::<TerrainTileMaterial>()
            .insert_resource(ReliefSettings::default())
            .insert_resource(TerrainTileCoverage::default())
            .insert_resource(TerrainTileDispatch::default())
            .insert_resource(QuadtreeSelection::default())
            .insert_resource(TileResidency::default())
            .insert_resource(TerrainGridMesh(Handle::default()))
            .insert_resource(fixture(64, 70))
            .add_systems(
                Update,
                initialize_gpu_world.run_if(resource_changed::<GeneratedWorld>),
            );
        app.update();
        let first = app.world().resource::<TerrainGpuResources>();
        let first_tile_assets = app.world().resource::<TerrainTileAssets>();
        let first_ids = (
            first.controls.id(),
            first.stamps.id(),
            first.parameters.id(),
            first.jobs.id(),
            first.addresses.id(),
            first.samples.id(),
            first_tile_assets.material.id(),
        );

        let stale_address =
            TileAddress::new(CubeFace::PositiveZ, TERRAIN_MAX_TILE_LEVEL, 0, 0).unwrap();
        let stale_entity = app.world_mut().spawn_empty().id();
        app.world_mut()
            .resource_mut::<TerrainTileCoverage>()
            .0
            .insert(
                ResidentTile {
                    address: stale_address,
                    slot: 0,
                },
                stale_entity,
            );

        app.insert_resource(fixture(64, 71));
        app.update();
        let second = app.world().resource::<TerrainGpuResources>();
        let second_tile_assets = app.world().resource::<TerrainTileAssets>();
        assert_ne!(
            first_ids,
            (
                second.controls.id(),
                second.stamps.id(),
                second.parameters.id(),
                second.jobs.id(),
                second.addresses.id(),
                second.samples.id(),
                second_tile_assets.material.id(),
            )
        );
        assert!(app.world().resource::<TerrainTileCoverage>().0.is_empty());
        assert_eq!(app.world().resource::<TileResidency>().resident_count(), 0);
        assert!(app.world().get_entity(stale_entity).is_err());
    }

    #[test]
    fn generation_jobs_match_the_named_two_vec4_shader_record() {
        let jobs = [
            ResidentTile {
                address: TileAddress::new(CubeFace::PositiveX, 4, 3, 5).unwrap(),
                slot: 17,
            },
            ResidentTile {
                address: TileAddress::new(CubeFace::NegativeZ, 12, 4_095, 3_000).unwrap(),
                slot: 311,
            },
        ];
        let encoded = generation_jobs(&jobs);
        assert_eq!(size_of::<TerrainTileJob>(), 32);
        assert_eq!(
            encoded,
            [
                TerrainTileJob {
                    address: [0, 4, 3, 5],
                    destination: [17, 0, 0, 0],
                },
                TerrainTileJob {
                    address: [5, 12, 4_095, 3_000],
                    destination: [311, 0, 0, 0],
                },
            ]
        );
    }

    #[test]
    fn mesh_tag_packs_child_parent_and_transition_weight() {
        let tile = ResidentTile {
            address: TileAddress::new(CubeFace::PositiveZ, 8, 17, 91).unwrap(),
            slot: 731,
        };
        let tag = terrain_mesh_tag(tile, 29, 0.375);
        assert_eq!(tag & TERRAIN_SLOT_MASK, tile.slot);
        assert_eq!((tag >> TERRAIN_SLOT_BITS) & TERRAIN_SLOT_MASK, 29);
        let quantized = tag >> (2 * TERRAIN_SLOT_BITS);
        assert!((quantized as f32 / TERRAIN_MORPH_MAX as f32 - 0.375).abs() < 0.000_13);
    }

    #[test]
    fn detailed_camera_sweep_fits_the_resident_capacity() {
        use super::residency::candidate_path;
        use std::collections::HashSet;

        let golden_angle = std::f32::consts::PI * (3.0 - 5.0_f32.sqrt());
        let mut maximum = 0;
        let mut previous_displayed = HashSet::new();
        for distance in [
            SURFACE_RADIUS + crate::camera::MIN_CAMERA_ALTITUDE,
            1.005,
            1.25,
            TERRAIN_TILE_ZOOM_THRESHOLD,
        ] {
            for index in 0..3_000 {
                let y = 1.0 - 2.0 * (index as f32 + 0.5) / 3_000.0;
                let radius = (1.0 - y * y).sqrt();
                let longitude = index as f32 * golden_angle;
                let direction = Vec3::new(radius * longitude.cos(), y, radius * longitude.sin());
                let position = direction * distance;
                let transform =
                    Transform::from_translation(position).looking_at(Vec3::ZERO, Vec3::Y);
                let view = CoverageView {
                    position,
                    forward: *transform.forward(),
                    right: *transform.right(),
                    up: *transform.up(),
                    vertical_fov: std::f32::consts::FRAC_PI_4,
                    aspect_ratio: 1.6,
                    viewport_height: 800.0,
                };
                let selected = QuadtreeSelection::default().select(view);
                let mut required = candidate_path(&selected)
                    .into_iter()
                    .collect::<HashSet<_>>();
                required.extend(previous_displayed.drain());
                maximum = maximum.max(required.len());
                previous_displayed.extend(selected);
            }
        }
        println!("maximum transient terrain residents in camera sweep: {maximum}");
        assert!(maximum <= MAX_RESIDENT_TILES);
    }
}
