mod compute;
mod coverage;
mod residency;

use std::sync::{
    Arc,
    atomic::{AtomicU32, Ordering},
};

use coverage::{CoverageView, QuadtreeSelection};
use residency::{ResidentTile, TileGeneration, TileResidency};

use super::{
    DiagnosticLayer, ReliefSettings, SURFACE_RADIUS, SurfaceSelection,
    palette::ELEVATION_COLOR_STOPS,
};
use crate::{camera::ViewerCamera, model::GeneratedWorld};
use bevy::{
    asset::{RenderAssetUsages, uuid_handle},
    camera::{Camera, Projection, visibility::NoFrustumCulling},
    ecs::system::SystemParam,
    mesh::{Indices, MeshTag, PrimitiveTopology},
    pbr::{ExtendedMaterial, MaterialExtension},
    prelude::*,
    render::{
        RenderApp,
        extract_resource::{ExtractResource, ExtractResourcePlugin},
        render_resource::{AsBindGroup, ShaderType},
        storage::ShaderStorageBuffer,
    },
    shader::{Shader, ShaderRef},
};
use procgen_cubesphere::{MAPPING_WGSL_SOURCE, TILE_QUADS, TILE_VERTICES};
use procgen_terrain::{
    TERRAIN_TILE_SAMPLE_COUNT, TERRAIN_WGSL_SOURCE, TerrainGpuParameters, TerrainGpuStamp,
    TerrainNoiseKeys, fixed_level_4_height_config, pack_control_bake, pack_stamps,
};

/// Camera distance at or below which adjusted elevation uses GPU terrain tiles.
const TERRAIN_TILE_ZOOM_THRESHOLD: f32 = 1.75;
const TERRAIN_MAX_TILE_LEVEL: u8 = 4;

const MAX_RESIDENT_TILES: usize = 512;
/// Maximum number of new terrain tiles generated by the viewer in one frame.
const NEW_TERRAIN_TILES_PER_FRAME: usize = 8;
const TERRAIN_SAMPLE_CAPACITY: usize = MAX_RESIDENT_TILES * TERRAIN_TILE_SAMPLE_COUNT;
const ELEVATION_PALETTE_STOP_COUNT: usize = ELEVATION_COLOR_STOPS.len();

const TERRAIN_VERTEX_SHADER: Handle<Shader> = uuid_handle!("f793fce0-ef68-49dd-8c98-7bba8432bc76");
const TERRAIN_COMPUTE_SHADER: Handle<Shader> = uuid_handle!("c7c57793-ae7c-4eb7-a1a9-9b8fb2d5a651");

#[derive(Clone, Copy, Debug, ShaderType)]
struct TerrainDisplayParameters {
    relief_exaggeration: f32,
    surface_radius: f32,
    padding: Vec2,
}

#[derive(Clone, Copy, Debug, ShaderType)]
struct TerrainElevationPalette {
    stops: [Vec4; ELEVATION_PALETTE_STOP_COUNT],
}

#[derive(Asset, AsBindGroup, Clone, Debug, TypePath)]
struct TerrainTileExtension {
    #[storage(100, read_only)]
    samples: Handle<ShaderStorageBuffer>,
    #[uniform(101)]
    display: TerrainDisplayParameters,
    #[uniform(102)]
    palette: TerrainElevationPalette,
}

impl MaterialExtension for TerrainTileExtension {
    fn vertex_shader() -> ShaderRef {
        TERRAIN_VERTEX_SHADER.into()
    }
}

type TerrainTileMaterial = ExtendedMaterial<StandardMaterial, TerrainTileExtension>;

#[derive(Resource, Clone, ExtractResource)]
struct TerrainGpuResources {
    controls: Handle<ShaderStorageBuffer>,
    stamps: Handle<ShaderStorageBuffer>,
    parameters: Handle<ShaderStorageBuffer>,
    jobs: Handle<ShaderStorageBuffer>,
    samples: Handle<ShaderStorageBuffer>,
}

#[derive(Resource)]
struct TerrainTileAssets {
    material: Handle<TerrainTileMaterial>,
}

#[derive(Resource, Clone, ExtractResource)]
struct TerrainTileDispatch {
    job_count: u32,
    generation: u32,
    completed_generation: Arc<AtomicU32>,
    pending: Vec<TileGeneration>,
}

impl Default for TerrainTileDispatch {
    fn default() -> Self {
        Self {
            job_count: 0,
            generation: 0,
            completed_generation: Arc::new(AtomicU32::new(u32::MAX)),
            pending: Vec::new(),
        }
    }
}

#[derive(Resource, Default)]
struct TerrainTileCoverage(Vec<(ResidentTile, Entity)>);

#[derive(Resource, Clone, Copy, Debug, Default, PartialEq, Eq)]
pub(super) enum TerrainTileMode {
    #[default]
    Coarse,
    Tiles,
}

#[derive(Resource)]
struct TerrainGridMesh(Handle<Mesh>);

pub(super) struct TerrainTileRenderPlugin;

impl Plugin for TerrainTileRenderPlugin {
    fn build(&self, app: &mut App) {
        register_shaders(app);
        app.add_plugins((
            MaterialPlugin::<TerrainTileMaterial>::default(),
            ExtractResourcePlugin::<TerrainGpuResources>::default(),
            ExtractResourcePlugin::<TerrainTileDispatch>::default(),
        ))
        .init_resource::<TerrainTileCoverage>()
        .init_resource::<TerrainTileDispatch>()
        .init_resource::<TerrainTileMode>()
        .init_resource::<QuadtreeSelection>()
        .init_resource::<TileResidency>()
        .add_systems(Startup, initialize_grid_mesh)
        .add_systems(
            Update,
            (
                initialize_gpu_world.run_if(resource_changed::<GeneratedWorld>),
                sync_mode.run_if(resource_changed::<SurfaceSelection>.or(camera_changed)),
                sync_relief.run_if(
                    resource_changed::<ReliefSettings>.and(resource_exists::<TerrainTileAssets>),
                ),
                update_tile_coverage,
            )
                .chain(),
        );

        compute::install(app.sub_app_mut(RenderApp));
    }
}

fn camera_changed(camera: Single<Ref<Transform>, With<ViewerCamera>>) -> bool {
    camera.is_changed()
}

pub(super) fn sync_mode(
    camera: Single<&Transform, With<ViewerCamera>>,
    selection: Res<SurfaceSelection>,
    mut mode: ResMut<TerrainTileMode>,
) {
    mode.set_if_neq(terrain_tile_mode(
        camera.translation.length(),
        selection.selected(),
    ));
}

fn initialize_grid_mesh(mut commands: Commands, mut meshes: ResMut<Assets<Mesh>>) {
    commands.insert_resource(TerrainGridMesh(meshes.add(tile_grid_mesh())));
}

fn register_shaders(app: &mut App) {
    let vertex_source = format!(
        "{MAPPING_WGSL_SOURCE}\nconst TERRAIN_ELEVATION_PALETTE_STOP_COUNT: u32 = {ELEVATION_PALETTE_STOP_COUNT}u;\n{}",
        include_str!("terrain_tiles.wgsl")
    );
    let compute_source = format!(
        "{TERRAIN_WGSL_SOURCE}\n{}",
        include_str!("terrain_compute.wgsl")
    );
    let mut shaders = app.world_mut().resource_mut::<Assets<Shader>>();
    shaders
        .insert(
            TERRAIN_VERTEX_SHADER.id(),
            Shader::from_wgsl(vertex_source, "procgen-terrain-viewer.wgsl"),
        )
        .unwrap();
    shaders
        .insert(
            TERRAIN_COMPUTE_SHADER.id(),
            Shader::from_wgsl(compute_source, "procgen-terrain-compute.wgsl"),
        )
        .unwrap();
}

#[derive(SystemParam)]
struct TerrainWorldAssets<'w, 's> {
    commands: Commands<'w, 's>,
    coverage: ResMut<'w, TerrainTileCoverage>,
    buffers: ResMut<'w, Assets<ShaderStorageBuffer>>,
    materials: ResMut<'w, Assets<TerrainTileMaterial>>,
    selection: ResMut<'w, QuadtreeSelection>,
    residency: ResMut<'w, TileResidency>,
    dispatch: ResMut<'w, TerrainTileDispatch>,
}

fn initialize_gpu_world(
    world: Res<GeneratedWorld>,
    relief: Res<ReliefSettings>,
    mut assets: TerrainWorldAssets,
) {
    for (_, entity) in assets.coverage.0.drain(..) {
        assets.commands.entity(entity).despawn();
    }
    assets.selection.clear();
    *assets.residency = TileResidency::default();
    *assets.dispatch = TerrainTileDispatch::default();

    let controls = pack_control_bake(&world.terrain_control_bake);
    let mut stamps = pack_stamps(&world.terrain_controls.stamps);
    // wgpu storage bindings cannot be empty; the shader reads no stamps when stamp_count is zero.
    if stamps.is_empty() {
        stamps.push(TerrainGpuStamp {
            position: [0.0; 3],
            strength: 0.0,
            kind: 0,
            padding: [0; 3],
        });
    }
    let parameters = TerrainGpuParameters::new(
        &world.terrain_control_bake,
        &world.terrain_controls.stamps,
        TerrainNoiseKeys::new(world.config.fibonacci.seed),
        fixed_level_4_height_config(),
    );
    let controls = assets.buffers.add(ShaderStorageBuffer::new(
        bytemuck::cast_slice(&controls),
        RenderAssetUsages::default(),
    ));
    let stamps = assets.buffers.add(ShaderStorageBuffer::new(
        bytemuck::cast_slice(&stamps),
        RenderAssetUsages::default(),
    ));
    let parameters = assets.buffers.add(ShaderStorageBuffer::new(
        bytemuck::bytes_of(&parameters),
        RenderAssetUsages::default(),
    ));
    let jobs = assets.buffers.add(ShaderStorageBuffer::from(vec![
        [0_u32; 8];
        NEW_TERRAIN_TILES_PER_FRAME
    ]));
    let samples = assets.buffers.add(ShaderStorageBuffer::with_size(
        TERRAIN_SAMPLE_CAPACITY * size_of::<Vec4>(),
        RenderAssetUsages::default(),
    ));
    let material = assets.materials.add(ExtendedMaterial {
        base: StandardMaterial {
            base_color: Color::WHITE,
            perceptual_roughness: 1.0,
            ..default()
        },
        extension: TerrainTileExtension {
            samples: samples.clone(),
            display: TerrainDisplayParameters {
                relief_exaggeration: relief.exaggeration,
                surface_radius: SURFACE_RADIUS,
                padding: Vec2::ZERO,
            },
            palette: elevation_palette(),
        },
    });
    assets.commands.insert_resource(TerrainGpuResources {
        controls,
        stamps,
        parameters,
        jobs,
        samples,
    });
    assets
        .commands
        .insert_resource(TerrainTileAssets { material });
}

fn elevation_palette() -> TerrainElevationPalette {
    TerrainElevationPalette {
        stops: std::array::from_fn(|index| {
            let (value, color) = ELEVATION_COLOR_STOPS[index];
            Vec4::new(color.x, color.y, color.z, value)
        }),
    }
}

#[derive(SystemParam)]
struct TerrainCoverageAssets<'w, 's> {
    commands: Commands<'w, 's>,
    grid: Res<'w, TerrainGridMesh>,
    coverage: ResMut<'w, TerrainTileCoverage>,
    selection: ResMut<'w, QuadtreeSelection>,
    residency: ResMut<'w, TileResidency>,
    resources: ResMut<'w, TerrainGpuResources>,
    tile_assets: Res<'w, TerrainTileAssets>,
    buffers: ResMut<'w, Assets<ShaderStorageBuffer>>,
}

fn sync_relief(
    relief: Res<ReliefSettings>,
    tile_assets: Res<TerrainTileAssets>,
    mut materials: ResMut<Assets<TerrainTileMaterial>>,
) {
    materials
        .get_mut(&tile_assets.material)
        .expect("terrain tile material must remain alive")
        .extension
        .display
        .relief_exaggeration = relief.exaggeration;
}

fn update_tile_coverage(
    camera: Single<(&Camera, &Projection, &Transform), With<ViewerCamera>>,
    mode: Res<TerrainTileMode>,
    mut dispatch: ResMut<TerrainTileDispatch>,
    mut assets: TerrainCoverageAssets,
) {
    if !dispatch.pending.is_empty()
        && dispatch.completed_generation.load(Ordering::Acquire) == dispatch.generation
    {
        assets.residency.complete(&dispatch.pending);
        dispatch.pending.clear();
        dispatch.job_count = 0;
    }
    let targets = if *mode == TerrainTileMode::Tiles {
        let (camera, projection, transform) = *camera;
        let Projection::Perspective(projection) = projection else {
            return;
        };
        let viewport_height = camera.logical_viewport_size().map_or(800.0, |size| size.y);
        assets.selection.select(CoverageView {
            position: transform.translation,
            forward: *transform.forward(),
            right: *transform.right(),
            up: *transform.up(),
            vertical_fov: projection.fov,
            aspect_ratio: projection.aspect_ratio,
            viewport_height,
        })
    } else {
        assets.selection.clear();
        Vec::new()
    };
    let update = assets.residency.update(&targets);
    upload_generation_jobs(&update.generated, &mut dispatch, &mut assets);
    sync_displayed_tiles(&update.displayed, &mut assets);
}

fn upload_generation_jobs(
    generated: &[TileGeneration],
    dispatch: &mut TerrainTileDispatch,
    assets: &mut TerrainCoverageAssets,
) {
    if generated.is_empty() || !dispatch.pending.is_empty() {
        return;
    }
    let mut encoded = vec![[0_u32; 8]; NEW_TERRAIN_TILES_PER_FRAME];
    for (job, output) in generated.iter().zip(&mut encoded) {
        output[..4].copy_from_slice(&job.address.gpu_words());
        output[4] = job.slot;
    }
    assets
        .buffers
        .get_mut(&assets.resources.jobs)
        .expect("terrain job buffer must remain alive")
        .set_data(encoded);
    dispatch.generation = dispatch.generation.wrapping_add(1);
    dispatch.job_count = generated.len() as u32;
    dispatch.pending.extend_from_slice(generated);
}

fn sync_displayed_tiles(displayed: &[ResidentTile], assets: &mut TerrainCoverageAssets) {
    let mut previous = std::mem::take(&mut assets.coverage.0);
    let mesh = assets.grid.0.clone();
    let material = assets.tile_assets.material.clone();
    assets.coverage.0 = displayed
        .iter()
        .copied()
        .map(|tile| {
            if let Some(index) = previous.iter().position(|(current, _)| *current == tile) {
                return previous.swap_remove(index);
            }
            let entity = assets
                .commands
                .spawn((
                    Mesh3d(mesh.clone()),
                    MeshMaterial3d(material.clone()),
                    MeshTag(pack_mesh_tag(tile)),
                    NoFrustumCulling,
                ))
                .id();
            (tile, entity)
        })
        .collect();
    for (_, entity) in previous {
        assets.commands.entity(entity).despawn();
    }
}

fn pack_mesh_tag(tile: ResidentTile) -> u32 {
    debug_assert!(tile.slot < MAX_RESIDENT_TILES as u32);
    debug_assert!(tile.address.level() <= TERRAIN_MAX_TILE_LEVEL);
    tile.slot
        | (tile.address.face().index() as u32) << 9
        | u32::from(tile.address.level()) << 12
        | tile.address.x() << 15
        | tile.address.y() << 19
}

fn terrain_tile_mode(camera_distance: f32, selected: Option<DiagnosticLayer>) -> TerrainTileMode {
    if camera_distance <= TERRAIN_TILE_ZOOM_THRESHOLD
        && selected == Some(DiagnosticLayer::IsostaticElevation)
    {
        TerrainTileMode::Tiles
    } else {
        TerrainTileMode::Coarse
    }
}

fn tile_grid_mesh() -> Mesh {
    // Integer grid coordinates are decoded by the custom vertex shader; normals and colors are
    // present only to select Bevy's lit, vertex-color mesh pipeline layout.
    let positions = (0..TILE_VERTICES)
        .flat_map(|y| (0..TILE_VERTICES).map(move |x| [x as f32, y as f32, 0.0]))
        .collect::<Vec<_>>();
    let normals = vec![[0.0, 0.0, 1.0]; positions.len()];
    let colors = vec![[1.0, 1.0, 1.0, 1.0]; positions.len()];
    let mut indices = Vec::with_capacity((TILE_QUADS * TILE_QUADS * 6) as usize);
    for y in 0..TILE_QUADS {
        for x in 0..TILE_QUADS {
            let lower_left = y * TILE_VERTICES + x;
            let lower_right = lower_left + 1;
            let upper_left = lower_left + TILE_VERTICES;
            let upper_right = upper_left + 1;
            indices.extend([
                lower_left,
                lower_right,
                upper_right,
                lower_left,
                upper_right,
                upper_left,
            ]);
        }
    }
    Mesh::new(
        PrimitiveTopology::TriangleList,
        RenderAssetUsages::default(),
    )
    .with_inserted_attribute(Mesh::ATTRIBUTE_POSITION, positions)
    .with_inserted_attribute(Mesh::ATTRIBUTE_NORMAL, normals)
    .with_inserted_attribute(Mesh::ATTRIBUTE_COLOR, colors)
    .with_inserted_indices(Indices::U32(indices))
}

#[cfg(test)]
mod tests {
    use super::*;
    use bevy::mesh::VertexAttributeValues;
    use procgen_cubesphere::{CubeFace, TileAddress};

    use super::coverage::tile_direction;

    #[test]
    fn tile_grid_triangles_face_outward_on_every_cube_face() {
        let mesh = tile_grid_mesh();
        let VertexAttributeValues::Float32x3(positions) =
            mesh.attribute(Mesh::ATTRIBUTE_POSITION).unwrap()
        else {
            panic!("terrain tile positions must be float3");
        };
        let Indices::U32(indices) = mesh.indices().unwrap() else {
            panic!("terrain tile indices must be u32");
        };

        for face in CubeFace::ALL {
            let address = TileAddress::new(face, 0, 0, 0).unwrap();
            for triangle in indices.chunks_exact(3) {
                let directions = [triangle[0], triangle[1], triangle[2]].map(|index| {
                    let [x, y, _] = positions[index as usize];
                    tile_direction(address, x as u32, y as u32)
                });
                let geometric_normal =
                    (directions[1] - directions[0]).cross(directions[2] - directions[0]);
                let center = (directions[0] + directions[1] + directions[2]).normalize();
                assert!(geometric_normal.dot(center) > 0.0);
            }
        }
    }

    #[test]
    fn mode_only_replaces_final_adjusted_elevation_below_threshold() {
        assert_eq!(
            terrain_tile_mode(
                TERRAIN_TILE_ZOOM_THRESHOLD,
                Some(DiagnosticLayer::IsostaticElevation)
            ),
            TerrainTileMode::Tiles
        );
        assert_eq!(
            terrain_tile_mode(
                TERRAIN_TILE_ZOOM_THRESHOLD + f32::EPSILON,
                Some(DiagnosticLayer::IsostaticElevation)
            ),
            TerrainTileMode::Coarse
        );
        assert_eq!(
            terrain_tile_mode(1.25, Some(DiagnosticLayer::GeologicalElevation)),
            TerrainTileMode::Coarse
        );
        assert_eq!(terrain_tile_mode(1.25, None), TerrainTileMode::Coarse);
    }

    #[test]
    fn mode_resource_changes_only_when_the_rendering_mode_changes() {
        let mut app = App::new();
        app.init_resource::<SurfaceSelection>()
            .init_resource::<TerrainTileMode>()
            .add_systems(Update, sync_mode);
        let camera = app
            .world_mut()
            .spawn((Transform::from_xyz(0.0, 0.0, 3.2), ViewerCamera))
            .id();

        app.update();
        assert_eq!(
            *app.world().resource::<TerrainTileMode>(),
            TerrainTileMode::Coarse
        );
        app.world_mut().clear_trackers();
        app.update();
        assert!(!app.world().resource_ref::<TerrainTileMode>().is_changed());

        app.world_mut()
            .entity_mut(camera)
            .get_mut::<Transform>()
            .unwrap()
            .translation = Vec3::Z * TERRAIN_TILE_ZOOM_THRESHOLD;
        app.update();
        assert_eq!(
            *app.world().resource::<TerrainTileMode>(),
            TerrainTileMode::Tiles
        );
    }

    #[test]
    fn world_replacement_resets_coverage_and_world_owned_gpu_resources() {
        use crate::test_support::fixture;
        use bevy::asset::{AssetApp, AssetPlugin};

        let mut app = App::new();
        app.add_plugins(AssetPlugin::default())
            .init_asset::<ShaderStorageBuffer>()
            .init_asset::<TerrainTileMaterial>()
            .insert_resource(ReliefSettings::default())
            .insert_resource(TerrainTileCoverage::default())
            .insert_resource(TerrainTileDispatch::default())
            .insert_resource(QuadtreeSelection::default())
            .insert_resource(TileResidency::default())
            .insert_resource(TerrainGridMesh(Handle::default()))
            .insert_resource(fixture(64, 70))
            .add_systems(
                Update,
                initialize_gpu_world.run_if(resource_changed::<GeneratedWorld>),
            );
        app.update();
        let first = app.world().resource::<TerrainGpuResources>();
        let first_tile_assets = app.world().resource::<TerrainTileAssets>();
        let first_ids = (
            first.controls.id(),
            first.stamps.id(),
            first.parameters.id(),
            first.jobs.id(),
            first.samples.id(),
            first_tile_assets.material.id(),
        );

        let stale_address =
            TileAddress::new(CubeFace::PositiveZ, TERRAIN_MAX_TILE_LEVEL, 0, 0).unwrap();
        let stale_entity = app.world_mut().spawn_empty().id();
        app.world_mut()
            .resource_mut::<TerrainTileCoverage>()
            .0
            .push((
                ResidentTile {
                    address: stale_address,
                    slot: 0,
                },
                stale_entity,
            ));

        app.insert_resource(fixture(64, 71));
        app.update();
        let second = app.world().resource::<TerrainGpuResources>();
        let second_tile_assets = app.world().resource::<TerrainTileAssets>();
        assert_ne!(
            first_ids,
            (
                second.controls.id(),
                second.stamps.id(),
                second.parameters.id(),
                second.jobs.id(),
                second.samples.id(),
                second_tile_assets.material.id(),
            )
        );
        assert!(app.world().resource::<TerrainTileCoverage>().0.is_empty());
        assert_eq!(app.world().resource::<TileResidency>().resident_count(), 0);
        assert!(app.world().get_entity(stale_entity).is_err());
    }

    #[test]
    fn mesh_tag_round_trips_the_slice_13_address_and_slot_ranges() {
        let tile = ResidentTile {
            address: TileAddress::new(CubeFace::NegativeY, 4, 15, 13).unwrap(),
            slot: 511,
        };
        let tag = pack_mesh_tag(tile);
        assert_eq!(tag & 0x1ff, tile.slot);
        assert_eq!((tag >> 9) & 0x7, tile.address.face().index() as u32);
        assert_eq!((tag >> 12) & 0x7, u32::from(tile.address.level()));
        assert_eq!((tag >> 15) & 0xf, tile.address.x());
        assert_eq!((tag >> 19) & 0xf, tile.address.y());
    }

    #[test]
    fn detailed_camera_sweep_fits_the_resident_capacity() {
        use super::residency::candidate_path;

        let golden_angle = std::f32::consts::PI * (3.0 - 5.0_f32.sqrt());
        let mut maximum = 0;
        for distance in [1.25, TERRAIN_TILE_ZOOM_THRESHOLD] {
            for index in 0..3_000 {
                let y = 1.0 - 2.0 * (index as f32 + 0.5) / 3_000.0;
                let radius = (1.0 - y * y).sqrt();
                let longitude = index as f32 * golden_angle;
                let direction = Vec3::new(radius * longitude.cos(), y, radius * longitude.sin());
                let position = direction * distance;
                let transform =
                    Transform::from_translation(position).looking_at(Vec3::ZERO, Vec3::Y);
                let view = CoverageView {
                    position,
                    forward: *transform.forward(),
                    right: *transform.right(),
                    up: *transform.up(),
                    vertical_fov: std::f32::consts::FRAC_PI_4,
                    aspect_ratio: 1.6,
                    viewport_height: 800.0,
                };
                let selected = QuadtreeSelection::default().select(view);
                maximum = maximum.max(candidate_path(&selected).len());
            }
        }
        println!("maximum required terrain residents in camera sweep: {maximum}");
        assert!(maximum <= MAX_RESIDENT_TILES);
    }
}
