mod compute;
mod coverage;
mod mesh;
mod residency;

use std::collections::HashMap;
use std::sync::{
    Arc,
    atomic::{AtomicU32, Ordering},
};

use coverage::{CoverageView, QuadtreeSelection, tile_morph_factor};
use mesh::{tile_grid_mesh, tile_origin};
use residency::{ResidentTile, TileResidency};

use super::{
    DiagnosticLayer, ReliefSettings, SURFACE_RADIUS, SurfaceSelection,
    palette::{ELEVATION_STOP_COUNT, elevation_color_stops},
};
use crate::camera::OrbitCamera;
use crate::model::GeneratedWorld;
use bevy::{
    asset::{RenderAssetUsages, uuid_handle},
    camera::{Camera, Projection, visibility::NoFrustumCulling},
    ecs::system::SystemParam,
    mesh::MeshTag,
    pbr::{ExtendedMaterial, MaterialExtension},
    prelude::*,
    render::{
        RenderApp,
        extract_resource::{ExtractResource, ExtractResourcePlugin},
        render_resource::{AsBindGroup, ShaderType},
        storage::ShaderStorageBuffer,
    },
    shader::{Shader, ShaderRef},
};
use procgen_cubesphere::MAPPING_WGSL_SOURCE;
use procgen_terrain::{
    TERRAIN_TILE_SAMPLE_COUNT, TERRAIN_WGSL_SOURCE, TerrainGpuParameters, TerrainHeightConfig,
    TerrainNoiseKeys, pack_control_bake, pack_stamps,
};

/// Camera distance at or below which adjusted elevation uses GPU terrain tiles.
const TERRAIN_TILE_ZOOM_THRESHOLD: f32 = 1.75;
const TERRAIN_MAX_TILE_LEVEL: u8 = 12;

/// Next power-of-two capacity above the measured 982-tile close-view handoff demand.
const MAX_RESIDENT_TILES: usize = 1_024;
/// Maximum number of new terrain tiles generated by the viewer in one frame.
const NEW_TERRAIN_TILES_PER_FRAME: usize = 8;
/// Radial skirt depth in units of the tile's nominal vertex spacing.
const TERRAIN_SKIRT_DEPTH_SPACINGS: f32 = 2.0;
const TERRAIN_SAMPLE_CAPACITY: usize = MAX_RESIDENT_TILES * TERRAIN_TILE_SAMPLE_COUNT;
const TERRAIN_SLOT_BITS: u32 = MAX_RESIDENT_TILES.trailing_zeros();
const TERRAIN_SLOT_MASK: u32 = MAX_RESIDENT_TILES as u32 - 1;
const TERRAIN_MORPH_BITS: u32 = u32::BITS - 2 * TERRAIN_SLOT_BITS;
const TERRAIN_MORPH_MAX: u32 = (1 << TERRAIN_MORPH_BITS) - 1;

const _: () = assert!(MAX_RESIDENT_TILES.is_power_of_two());

const TERRAIN_VERTEX_SHADER: Handle<Shader> = uuid_handle!("f793fce0-ef68-49dd-8c98-7bba8432bc76");
const TERRAIN_COMPUTE_SHADER: Handle<Shader> = uuid_handle!("c7c57793-ae7c-4eb7-a1a9-9b8fb2d5a651");

#[derive(Clone, Copy, Debug, ShaderType)]
struct TerrainDisplayParameters {
    relief_exaggeration: f32,
    surface_radius: f32,
    padding: Vec2,
}

#[derive(Clone, Copy, Debug, ShaderType)]
struct TerrainElevationPalette {
    stops: [Vec4; ELEVATION_STOP_COUNT],
}

#[derive(Asset, AsBindGroup, Clone, Debug, TypePath)]
struct TerrainTileExtension {
    #[storage(100, read_only)]
    addresses: Handle<ShaderStorageBuffer>,
    #[storage(101, read_only)]
    samples: Handle<ShaderStorageBuffer>,
    #[uniform(102)]
    display: TerrainDisplayParameters,
    #[uniform(103)]
    palette: TerrainElevationPalette,
}

impl MaterialExtension for TerrainTileExtension {
    fn vertex_shader() -> ShaderRef {
        TERRAIN_VERTEX_SHADER.into()
    }
}

type TerrainTileMaterial = ExtendedMaterial<StandardMaterial, TerrainTileExtension>;

#[derive(Resource, Clone, ExtractResource)]
struct TerrainGpuResources {
    controls: Handle<ShaderStorageBuffer>,
    stamps: Handle<ShaderStorageBuffer>,
    parameters: Handle<ShaderStorageBuffer>,
    jobs: Handle<ShaderStorageBuffer>,
    addresses: Handle<ShaderStorageBuffer>,
    samples: Handle<ShaderStorageBuffer>,
}

#[derive(Resource)]
struct TerrainTileAssets {
    material: Handle<TerrainTileMaterial>,
}

#[derive(Resource, Clone, ExtractResource, Default)]
struct TerrainTileDispatch {
    job_count: u32,
    generation: u32,
    completed_generation: Arc<AtomicU32>,
}

impl TerrainTileDispatch {
    fn is_complete(&self) -> bool {
        self.completed_generation.load(Ordering::Acquire) == self.generation
    }
}

#[repr(C, align(16))]
#[derive(Clone, Copy, Debug, PartialEq, Eq, bytemuck::Pod, bytemuck::Zeroable)]
struct TerrainTileJob {
    address: [u32; 4],
    destination: [u32; 4],
}

#[derive(Resource, Default)]
struct TerrainTileCoverage(HashMap<ResidentTile, Entity>);

#[derive(Resource, Clone, Copy, Debug, Default, PartialEq, Eq)]
pub(super) enum TerrainTileMode {
    #[default]
    Coarse,
    Tiles,
}

#[derive(Resource)]
struct TerrainGridMesh(Handle<Mesh>);

pub(super) struct TerrainTileRenderPlugin;

impl Plugin for TerrainTileRenderPlugin {
    fn build(&self, app: &mut App) {
        register_shaders(app);
        app.add_plugins((
            MaterialPlugin::<TerrainTileMaterial>::default(),
            ExtractResourcePlugin::<TerrainGpuResources>::default(),
            ExtractResourcePlugin::<TerrainTileDispatch>::default(),
        ))
        .init_resource::<TerrainTileCoverage>()
        .init_resource::<TerrainTileDispatch>()
        .init_resource::<TerrainTileMode>()
        .init_resource::<QuadtreeSelection>()
        .init_resource::<TileResidency>()
        .add_systems(Startup, initialize_grid_mesh)
        .add_systems(
            Update,
            (
                initialize_gpu_world.run_if(resource_changed::<GeneratedWorld>),
                sync_mode.run_if(resource_changed::<SurfaceSelection>.or(camera_changed)),
                sync_relief.run_if(
                    resource_changed::<ReliefSettings>.and(resource_exists::<TerrainTileAssets>),
                ),
                update_tile_coverage
                    .run_if(resource_exists::<TerrainTileAssets>)
                    .run_if(
                        resource_changed::<GeneratedWorld>
                            .or(resource_changed::<TerrainTileMode>)
                            .or(camera_changed)
                            .or(terrain_dispatch_completed),
                    ),
            )
                .chain(),
        );

        compute::install(app.sub_app_mut(RenderApp));
    }
}

fn camera_changed(camera: Single<Ref<Transform>, With<OrbitCamera>>) -> bool {
    camera.is_changed()
}

fn terrain_dispatch_completed(
    dispatch: Res<TerrainTileDispatch>,
    mut observed: Local<u32>,
) -> bool {
    let changed = dispatch.is_complete() && dispatch.generation != *observed;
    if changed {
        *observed = dispatch.generation;
    }
    changed
}

pub(super) fn sync_mode(
    camera: Single<&Transform, With<OrbitCamera>>,
    selection: Res<SurfaceSelection>,
    mut mode: ResMut<TerrainTileMode>,
) {
    mode.set_if_neq(terrain_tile_mode(
        camera.translation.length(),
        selection.selected(),
    ));
}

fn initialize_grid_mesh(mut commands: Commands, mut meshes: ResMut<Assets<Mesh>>) {
    commands.insert_resource(TerrainGridMesh(meshes.add(tile_grid_mesh())));
}

fn register_shaders(app: &mut App) {
    let vertex_constants = format!(
        "const TERRAIN_ELEVATION_PALETTE_STOP_COUNT: u32 = {ELEVATION_STOP_COUNT}u;\n\
         const TERRAIN_SKIRT_DEPTH_SPACINGS: f32 = {TERRAIN_SKIRT_DEPTH_SPACINGS};\n\
         const TERRAIN_SLOT_BITS: u32 = {TERRAIN_SLOT_BITS}u;\n\
         const TERRAIN_SLOT_MASK: u32 = {TERRAIN_SLOT_MASK}u;\n\
         const TERRAIN_MORPH_MAX: u32 = {TERRAIN_MORPH_MAX}u;"
    );
    let vertex_source = [
        MAPPING_WGSL_SOURCE.to_owned(),
        vertex_constants,
        include_str!("terrain_tiles.wgsl").to_owned(),
    ]
    .join("\n");
    let compute_source = [
        TERRAIN_WGSL_SOURCE.to_owned(),
        include_str!("terrain_compute.wgsl").to_owned(),
    ]
    .join("\n");
    let mut shaders = app.world_mut().resource_mut::<Assets<Shader>>();
    shaders
        .insert(
            TERRAIN_VERTEX_SHADER.id(),
            Shader::from_wgsl(vertex_source, "procgen-terrain-viewer.wgsl"),
        )
        .unwrap();
    shaders
        .insert(
            TERRAIN_COMPUTE_SHADER.id(),
            Shader::from_wgsl(compute_source, "procgen-terrain-compute.wgsl"),
        )
        .unwrap();
}

#[derive(SystemParam)]
struct TerrainWorldAssets<'w, 's> {
    commands: Commands<'w, 's>,
    coverage: ResMut<'w, TerrainTileCoverage>,
    buffers: ResMut<'w, Assets<ShaderStorageBuffer>>,
    materials: ResMut<'w, Assets<TerrainTileMaterial>>,
    selection: ResMut<'w, QuadtreeSelection>,
    residency: ResMut<'w, TileResidency>,
    dispatch: ResMut<'w, TerrainTileDispatch>,
}

fn initialize_gpu_world(
    world: Res<GeneratedWorld>,
    relief: Res<ReliefSettings>,
    mut assets: TerrainWorldAssets,
) {
    for (_, entity) in assets.coverage.0.drain() {
        assets.commands.entity(entity).despawn();
    }
    assets.selection.clear();
    *assets.residency = TileResidency::default();
    assets.dispatch.job_count = 0;
    assets.dispatch.generation = assets.dispatch.generation.wrapping_add(1);

    // Detailed tiles read the geology phase's baked terrain controls, so
    // dropping geology drops the buffers and material built from it.
    let (Some(tectonics), Some(geology)) = (world.tectonics(), world.geology()) else {
        assets.commands.remove_resource::<TerrainGpuResources>();
        assets.commands.remove_resource::<TerrainTileAssets>();
        return;
    };
    let controls = pack_control_bake(&geology.terrain_control_bake);
    let stamps = pack_stamps(&geology.terrain_controls.stamps);
    // The bake descends from the isostatic field, so its datum is the one the
    // detailed surface is measured against.
    let sea_level = geology.isostasy.sea_level;
    let parameters = TerrainGpuParameters::new(
        &geology.terrain_control_bake,
        &geology.terrain_controls.stamps,
        TerrainNoiseKeys::new(tectonics.config.fibonacci.seed),
        sea_level,
        TerrainHeightConfig::default(),
    );
    let controls = assets.buffers.add(ShaderStorageBuffer::new(
        bytemuck::cast_slice(&controls),
        RenderAssetUsages::default(),
    ));
    let stamps = assets.buffers.add(ShaderStorageBuffer::new(
        bytemuck::cast_slice(&stamps),
        RenderAssetUsages::default(),
    ));
    let parameters = assets.buffers.add(ShaderStorageBuffer::new(
        bytemuck::bytes_of(&parameters),
        RenderAssetUsages::default(),
    ));
    // wgpu storage bindings cannot be empty; this placeholder is never dispatched.
    let jobs = assets.buffers.add(ShaderStorageBuffer::new(
        bytemuck::bytes_of(&TerrainTileJob {
            address: [0; 4],
            destination: [0; 4],
        }),
        RenderAssetUsages::default(),
    ));
    let addresses = assets.buffers.add(ShaderStorageBuffer::with_size(
        MAX_RESIDENT_TILES * size_of::<[u32; 4]>(),
        RenderAssetUsages::default(),
    ));
    let samples = assets.buffers.add(ShaderStorageBuffer::with_size(
        TERRAIN_SAMPLE_CAPACITY * size_of::<Vec4>(),
        RenderAssetUsages::default(),
    ));
    let material = assets.materials.add(ExtendedMaterial {
        base: StandardMaterial {
            base_color: Color::WHITE,
            perceptual_roughness: 1.0,
            ..default()
        },
        extension: TerrainTileExtension {
            addresses: addresses.clone(),
            samples: samples.clone(),
            display: TerrainDisplayParameters {
                relief_exaggeration: relief.exaggeration,
                surface_radius: SURFACE_RADIUS,
                padding: Vec2::ZERO,
            },
            palette: elevation_palette(sea_level),
        },
    });
    assets.commands.insert_resource(TerrainGpuResources {
        controls,
        stamps,
        parameters,
        jobs,
        addresses,
        samples,
    });
    assets
        .commands
        .insert_resource(TerrainTileAssets { material });
}

fn elevation_palette(sea_level: f32) -> TerrainElevationPalette {
    let stops = elevation_color_stops(sea_level);
    TerrainElevationPalette {
        stops: stops.map(|(value, color)| Vec4::new(color.x, color.y, color.z, value)),
    }
}

#[derive(SystemParam)]
struct TerrainCoverageAssets<'w, 's> {
    commands: Commands<'w, 's>,
    grid: Res<'w, TerrainGridMesh>,
    coverage: ResMut<'w, TerrainTileCoverage>,
    selection: ResMut<'w, QuadtreeSelection>,
    residency: ResMut<'w, TileResidency>,
    dispatch: ResMut<'w, TerrainTileDispatch>,
    resources: ResMut<'w, TerrainGpuResources>,
    tile_assets: Res<'w, TerrainTileAssets>,
    buffers: ResMut<'w, Assets<ShaderStorageBuffer>>,
}

fn sync_relief(
    relief: Res<ReliefSettings>,
    tile_assets: Res<TerrainTileAssets>,
    mut materials: ResMut<Assets<TerrainTileMaterial>>,
) {
    materials
        .get_mut(&tile_assets.material)
        .expect("terrain tile material must remain alive")
        .extension
        .display
        .relief_exaggeration = relief.exaggeration;
}

fn update_tile_coverage(
    camera: Single<(&Camera, &Projection, &Transform), With<OrbitCamera>>,
    mode: Res<TerrainTileMode>,
    mut assets: TerrainCoverageAssets,
) {
    if assets.dispatch.is_complete() {
        assets.residency.complete_in_flight();
    }
    if *mode == TerrainTileMode::Coarse {
        assets.selection.clear();
        let update = assets.residency.update(&[]);
        upload_generation_jobs(&update.generated, &mut assets);
        clear_displayed_tiles(&mut assets);
        return;
    }

    let (camera, projection, transform) = *camera;
    let Some(view) = CoverageView::from_camera(camera, projection, transform) else {
        return;
    };
    let targets = assets.selection.select(view);
    let update = assets.residency.update(&targets);
    upload_generation_jobs(&update.generated, &mut assets);
    sync_displayed_tiles(&update.displayed, view, &mut assets);
}

fn clear_displayed_tiles(assets: &mut TerrainCoverageAssets<'_, '_>) {
    for (_, entity) in assets.coverage.0.drain() {
        assets.commands.entity(entity).despawn();
    }
}

fn upload_generation_jobs(generated: &[ResidentTile], assets: &mut TerrainCoverageAssets) {
    if generated.is_empty() {
        return;
    }
    assets.resources.jobs = assets.buffers.add(ShaderStorageBuffer::new(
        bytemuck::cast_slice(&generation_jobs(generated)),
        RenderAssetUsages::default(),
    ));
    assets.dispatch.generation = assets.dispatch.generation.wrapping_add(1);
    assets.dispatch.job_count = generated.len() as u32;
}

fn generation_jobs(generated: &[ResidentTile]) -> Vec<TerrainTileJob> {
    generated
        .iter()
        .map(|tile| TerrainTileJob {
            address: tile.address.gpu_words(),
            destination: [tile.slot, 0, 0, 0],
        })
        .collect()
}

fn sync_displayed_tiles(
    displayed: &[ResidentTile],
    view: CoverageView,
    assets: &mut TerrainCoverageAssets,
) {
    let mut previous = std::mem::take(&mut assets.coverage.0);
    let mesh = assets.grid.0.clone();
    let material = assets.tile_assets.material.clone();
    assets.coverage.0 = displayed
        .iter()
        .copied()
        .map(|tile| {
            let (parent_slot, morph) = match assets.residency.ready_parent_slot(tile) {
                Some(parent_slot) => (parent_slot, tile_morph_factor(tile.address, view)),
                // Root tiles and merge fallbacks have no ready parent to sample.
                None => (tile.slot, 1.0),
            };
            let tag = terrain_mesh_tag(tile, parent_slot, morph);
            if let Some(entity) = previous.remove(&tile) {
                assets.commands.entity(entity).insert(MeshTag(tag));
                return (tile, entity);
            }
            let entity = assets
                .commands
                .spawn((
                    Mesh3d(mesh.clone()),
                    MeshMaterial3d(material.clone()),
                    MeshTag(tag),
                    Transform::from_translation(tile_origin(tile.address)),
                    NoFrustumCulling,
                ))
                .id();
            (tile, entity)
        })
        .collect();
    for (_, entity) in previous {
        assets.commands.entity(entity).despawn();
    }
}

fn terrain_mesh_tag(tile: ResidentTile, parent_slot: u32, morph: f32) -> u32 {
    assert!(tile.slot <= TERRAIN_SLOT_MASK);
    assert!(parent_slot <= TERRAIN_SLOT_MASK);
    assert!(morph.is_finite() && (0.0..=1.0).contains(&morph));
    let quantized_morph = (morph * TERRAIN_MORPH_MAX as f32).round() as u32;
    tile.slot | (parent_slot << TERRAIN_SLOT_BITS) | (quantized_morph << (2 * TERRAIN_SLOT_BITS))
}

fn terrain_tile_mode(camera_distance: f32, selected: Option<DiagnosticLayer>) -> TerrainTileMode {
    if camera_distance <= TERRAIN_TILE_ZOOM_THRESHOLD
        && selected == Some(DiagnosticLayer::IsostaticElevation)
    {
        TerrainTileMode::Tiles
    } else {
        TerrainTileMode::Coarse
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use procgen_cubesphere::{CubeFace, TileAddress};

    #[test]
    fn mode_only_replaces_final_adjusted_elevation_below_threshold() {
        assert_eq!(
            terrain_tile_mode(
                TERRAIN_TILE_ZOOM_THRESHOLD,
                Some(DiagnosticLayer::IsostaticElevation)
            ),
            TerrainTileMode::Tiles
        );
        assert_eq!(
            terrain_tile_mode(
                TERRAIN_TILE_ZOOM_THRESHOLD + f32::EPSILON,
                Some(DiagnosticLayer::IsostaticElevation)
            ),
            TerrainTileMode::Coarse
        );
        assert_eq!(
            terrain_tile_mode(1.25, Some(DiagnosticLayer::GeologicalElevation)),
            TerrainTileMode::Coarse
        );
        assert_eq!(terrain_tile_mode(1.25, None), TerrainTileMode::Coarse);
    }

    #[test]
    fn mode_resource_changes_only_when_the_rendering_mode_changes() {
        let mut app = App::new();
        app.init_resource::<SurfaceSelection>()
            .init_resource::<TerrainTileMode>()
            .add_systems(Update, sync_mode);
        let camera = app
            .world_mut()
            .spawn((Transform::from_xyz(0.0, 0.0, 3.2), OrbitCamera))
            .id();

        app.update();
        assert_eq!(
            *app.world().resource::<TerrainTileMode>(),
            TerrainTileMode::Coarse
        );
        app.world_mut().clear_trackers();
        app.update();
        assert!(!app.world().resource_ref::<TerrainTileMode>().is_changed());

        app.world_mut()
            .entity_mut(camera)
            .get_mut::<Transform>()
            .unwrap()
            .translation = Vec3::Z * TERRAIN_TILE_ZOOM_THRESHOLD;
        app.update();
        assert_eq!(
            *app.world().resource::<TerrainTileMode>(),
            TerrainTileMode::Tiles
        );
    }

    #[test]
    fn completion_condition_runs_once_per_finished_generation() {
        #[derive(Resource, Default)]
        struct Runs(u32);

        fn count_run(mut runs: ResMut<Runs>) {
            runs.0 += 1;
        }

        let mut app = App::new();
        app.init_resource::<TerrainTileDispatch>()
            .init_resource::<Runs>()
            .add_systems(Update, count_run.run_if(terrain_dispatch_completed));
        app.update();
        assert_eq!(app.world().resource::<Runs>().0, 0);

        let mut dispatch = app.world_mut().resource_mut::<TerrainTileDispatch>();
        dispatch.generation = 1;
        dispatch.completed_generation.store(1, Ordering::Release);
        app.update();
        app.update();
        assert_eq!(app.world().resource::<Runs>().0, 1);

        let mut dispatch = app.world_mut().resource_mut::<TerrainTileDispatch>();
        dispatch.generation = 2;
        app.update();
        assert_eq!(app.world().resource::<Runs>().0, 1);
        app.world()
            .resource::<TerrainTileDispatch>()
            .completed_generation
            .store(2, Ordering::Release);
        app.update();
        assert_eq!(app.world().resource::<Runs>().0, 2);
    }

    #[test]
    fn world_replacement_resets_coverage_and_world_owned_gpu_resources() {
        use crate::test_support::Fixture;
        use bevy::asset::{AssetApp, AssetPlugin};

        let mut app = App::new();
        app.add_plugins(AssetPlugin::default())
            .init_asset::<ShaderStorageBuffer>()
            .init_asset::<TerrainTileMaterial>()
            .insert_resource(ReliefSettings::default())
            .insert_resource(TerrainTileCoverage::default())
            .insert_resource(TerrainTileDispatch::default())
            .insert_resource(QuadtreeSelection::default())
            .insert_resource(TileResidency::default())
            .insert_resource(TerrainGridMesh(Handle::default()))
            .insert_resource(Fixture::new(64, 71).into_world())
            .add_systems(
                Update,
                initialize_gpu_world.run_if(resource_changed::<GeneratedWorld>),
            );
        app.update();
        let first = app.world().resource::<TerrainGpuResources>();
        let first_tile_assets = app.world().resource::<TerrainTileAssets>();
        let first_ids = (
            first.controls.id(),
            first.stamps.id(),
            first.parameters.id(),
            first.jobs.id(),
            first.addresses.id(),
            first.samples.id(),
            first_tile_assets.material.id(),
        );

        let stale_address =
            TileAddress::new(CubeFace::PositiveZ, TERRAIN_MAX_TILE_LEVEL, 0, 0).unwrap();
        let stale_entity = app.world_mut().spawn_empty().id();
        app.world_mut()
            .resource_mut::<TerrainTileCoverage>()
            .0
            .insert(
                ResidentTile {
                    address: stale_address,
                    slot: 0,
                },
                stale_entity,
            );

        app.insert_resource(Fixture::new(64, 72).into_world());
        app.update();
        let second = app.world().resource::<TerrainGpuResources>();
        let second_tile_assets = app.world().resource::<TerrainTileAssets>();
        assert_ne!(
            first_ids,
            (
                second.controls.id(),
                second.stamps.id(),
                second.parameters.id(),
                second.jobs.id(),
                second.addresses.id(),
                second.samples.id(),
                second_tile_assets.material.id(),
            )
        );
        assert!(app.world().resource::<TerrainTileCoverage>().0.is_empty());
        assert_eq!(app.world().resource::<TileResidency>().resident_count(), 0);
        assert!(app.world().get_entity(stale_entity).is_err());
    }

    #[test]
    fn generation_jobs_match_the_named_two_vec4_shader_record() {
        let jobs = [
            ResidentTile {
                address: TileAddress::new(CubeFace::PositiveX, 4, 3, 5).unwrap(),
                slot: 17,
            },
            ResidentTile {
                address: TileAddress::new(CubeFace::NegativeZ, 12, 4_095, 3_000).unwrap(),
                slot: 311,
            },
        ];
        let encoded = generation_jobs(&jobs);
        assert_eq!(size_of::<TerrainTileJob>(), 32);
        assert_eq!(
            encoded,
            [
                TerrainTileJob {
                    address: [0, 4, 3, 5],
                    destination: [17, 0, 0, 0],
                },
                TerrainTileJob {
                    address: [5, 12, 4_095, 3_000],
                    destination: [311, 0, 0, 0],
                },
            ]
        );
    }

    #[test]
    fn mesh_tag_packs_child_parent_and_transition_weight() {
        let tile = ResidentTile {
            address: TileAddress::new(CubeFace::PositiveZ, 8, 17, 91).unwrap(),
            slot: 731,
        };
        let tag = terrain_mesh_tag(tile, 29, 0.375);
        assert_eq!(tag & TERRAIN_SLOT_MASK, tile.slot);
        assert_eq!((tag >> TERRAIN_SLOT_BITS) & TERRAIN_SLOT_MASK, 29);
        let quantized = tag >> (2 * TERRAIN_SLOT_BITS);
        assert!((quantized as f32 / TERRAIN_MORPH_MAX as f32 - 0.375).abs() < 0.000_13);
    }

    #[test]
    fn detailed_camera_sweep_fits_the_resident_capacity() {
        use super::residency::candidate_path;
        use std::collections::HashSet;

        let golden_angle = std::f32::consts::PI * (3.0 - 5.0_f32.sqrt());
        let mut maximum = 0;
        let mut previous_displayed = HashSet::new();
        for distance in [
            SURFACE_RADIUS + crate::camera::MIN_CAMERA_ALTITUDE,
            1.005,
            1.25,
            TERRAIN_TILE_ZOOM_THRESHOLD,
        ] {
            for index in 0..3_000 {
                let y = 1.0 - 2.0 * (index as f32 + 0.5) / 3_000.0;
                let radius = (1.0 - y * y).sqrt();
                let longitude = index as f32 * golden_angle;
                let direction = Vec3::new(radius * longitude.cos(), y, radius * longitude.sin());
                let position = direction * distance;
                let transform =
                    Transform::from_translation(position).looking_at(Vec3::ZERO, Vec3::Y);
                let view = CoverageView {
                    position,
                    forward: *transform.forward(),
                    right: *transform.right(),
                    up: *transform.up(),
                    vertical_fov: std::f32::consts::FRAC_PI_4,
                    aspect_ratio: 1.6,
                    viewport_height: 800.0,
                };
                let selected = QuadtreeSelection::default().select(view);
                let mut required = candidate_path(&selected)
                    .into_iter()
                    .collect::<HashSet<_>>();
                required.extend(previous_displayed.drain());
                maximum = maximum.max(required.len());
                previous_displayed.extend(selected);
            }
        }
        println!("maximum transient terrain residents in camera sweep: {maximum}");
        assert!(maximum <= MAX_RESIDENT_TILES);
    }
}
