[package]
name = "procgen-gpu-tests"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
bytemuck = { version = "1.24", features = ["derive"] }
wgpu = { version = "27.0.1", default-features = false, features = [
    "dx12",
    "metal",
    "std",
    "vulkan",
    "wgsl",
] }

[dev-dependencies]
procgen-core = { path = "../procgen-core" }
procgen-cubesphere = { path = "../procgen-cubesphere" }
procgen-noise = { path = "../procgen-noise" }
procgen-raster-tectonics = { path = "../procgen-raster-tectonics" }
procgen-tectonics = { path = "../procgen-tectonics" }
procgen-terrain = { path = "../procgen-terrain" }
